apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testmydom-org
  namespace: argocd
spec:
  secretName: testmydom-org-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: testmydom.org
  dnsNames:
    - testmydom.org
    - '*.testmydom.org'